/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package problemaelevador;

import java.awt.Font;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.JRadioButton;

/**
 *
 * @author elrafa
 */
public class interfacePainel extends javax.swing.JFrame {
    Edificio edificio;
    /**
     * Creates new form interfacePainel
     */
    public interfacePainel() {
       // initComponents();
        int numeroDePisos = 10;
        int quantidadeTrilhas = 5;
        float pesoMax = 1000;
        Credencial credenciais = new Credencial(numeroDePisos);
        
        credenciais.novaCredencial(1, "abc");
        credenciais.novaCredencial(1, "bca");
        credenciais.novaCredencial(1, "cab");
        credenciais.novaCredencial(2, "aaa");
        credenciais.novaCredencial(2, "bbb");
        credenciais.novaCredencial(3, "ccc");
        credenciais.novaCredencial(3, "ddd");
        credenciais.novaCredencial(3, "ccd");
        credenciais.novaCredencial(4, "ddc");
        credenciais.novaCredencial(4, "eee");
        credenciais.novaCredencial(4, "eee");
        credenciais.novaCredencial(5, "fff");
        credenciais.novaCredencial(5, "ffe");
        credenciais.novaCredencial(6, "fee");
        //Instanciando o novo EdifÃ­cio.
        
        edificio = new Edificio("INF PrÃ©dio 2", "CÃ¢mpus Samambaia", numeroDePisos, quantidadeTrilhas, credenciais, pesoMax );
        
        //edificio.setMusicInElevator(1, "Horse with no name");
        //edificio.setMusicInElevator(2, "Alegro");
        edificio.setMusicInElevator(3, "InquietaÃ§Ã£o");
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jRadioButton7 = new javax.swing.JRadioButton();
        jRadioButton8 = new javax.swing.JRadioButton();
        jRadioButton9 = new javax.swing.JRadioButton();
        jRadioButton10 = new javax.swing.JRadioButton();
        jRadioButton11 = new javax.swing.JRadioButton();
        chamaElevadorPainel = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        painelDoPainel = new javax.swing.JTextArea();
        jRadioButton12 = new javax.swing.JRadioButton();
        jRadioButton13 = new javax.swing.JRadioButton();
        jRadioButton14 = new javax.swing.JRadioButton();
        jRadioButton15 = new javax.swing.JRadioButton();
        jRadioButton16 = new javax.swing.JRadioButton();
        jRadioButton17 = new javax.swing.JRadioButton();
        jRadioButton18 = new javax.swing.JRadioButton();
        jRadioButton19 = new javax.swing.JRadioButton();
        jRadioButton20 = new javax.swing.JRadioButton();
        jRadioButton21 = new javax.swing.JRadioButton();
        jRadioButton22 = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setText("Térreo");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setText("1");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setText("2");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setText("3");

        buttonGroup1.add(jRadioButton5);
        jRadioButton5.setText("4");

        buttonGroup1.add(jRadioButton6);
        jRadioButton6.setText("5");

        buttonGroup1.add(jRadioButton7);
        jRadioButton7.setText("6");

        buttonGroup1.add(jRadioButton8);
        jRadioButton8.setText("7");

        buttonGroup1.add(jRadioButton9);
        jRadioButton9.setText("8");

        buttonGroup1.add(jRadioButton10);
        jRadioButton10.setText("9");

        buttonGroup1.add(jRadioButton11);
        jRadioButton11.setText("10");

        chamaElevadorPainel.setText("Chamar Elevador");
        chamaElevadorPainel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chamaElevadorPainelActionPerformed(evt);
            }
        });

        painelDoPainel.setEditable(false);
        painelDoPainel.setColumns(20);
        painelDoPainel.setRows(5);
        painelDoPainel.setAutoscrolls(false);
        jScrollPane1.setViewportView(painelDoPainel);

        buttonGroup2.add(jRadioButton12);
        jRadioButton12.setText("Térreo");

        buttonGroup2.add(jRadioButton13);
        jRadioButton13.setText("1");

        buttonGroup2.add(jRadioButton14);
        jRadioButton14.setText("2");

        buttonGroup2.add(jRadioButton15);
        jRadioButton15.setText("3");

        buttonGroup2.add(jRadioButton16);
        jRadioButton16.setText("4");

        buttonGroup2.add(jRadioButton17);
        jRadioButton17.setText("5");

        buttonGroup2.add(jRadioButton18);
        jRadioButton18.setText("6");

        buttonGroup2.add(jRadioButton19);
        jRadioButton19.setText("7");

        buttonGroup2.add(jRadioButton20);
        jRadioButton20.setText("8");

        buttonGroup2.add(jRadioButton21);
        jRadioButton21.setText("9");

        buttonGroup2.add(jRadioButton22);
        jRadioButton22.setText("10");

        jLabel2.setText("Onde você está?");

        jLabel3.setText("Para onde deseja ir?");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton9))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton11))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton5))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton7))
                    .addComponent(jRadioButton1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 80, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton19)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton20))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton13)
                        .addGap(18, 18, 18)
                        .addComponent(jRadioButton14))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jRadioButton22))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton16))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jRadioButton17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jRadioButton18))
                    .addComponent(jRadioButton12)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(99, 99, 99)
                .addComponent(chamaElevadorPainel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(126, 126, 126))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton1)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton2)
                                    .addComponent(jRadioButton3))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton4)
                                    .addComponent(jRadioButton5))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton6)
                                    .addComponent(jRadioButton7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton8)
                                    .addComponent(jRadioButton9))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton10)
                                    .addComponent(jRadioButton11)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jRadioButton12)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton13)
                                    .addComponent(jRadioButton14))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton15)
                                    .addComponent(jRadioButton16))
                                .addGap(12, 12, 12)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton17)
                                    .addComponent(jRadioButton18))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton19)
                                    .addComponent(jRadioButton20))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jRadioButton21)
                                    .addComponent(jRadioButton22))))
                        .addGap(18, 18, 18)))
                .addComponent(chamaElevadorPainel)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chamaElevadorPainelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chamaElevadorPainelActionPerformed
        int i=0;
        int j=0;
        Enumeration<AbstractButton> manage = this.buttonGroup1.getElements();
        for(i=0; i < this.buttonGroup1.getButtonCount(); i++){
           // System.out.println(this.buttonGroup1.getSelection() + "   " + this.buttonGroup1.getElements().nextElement());
          if(manage.nextElement().isSelected()) break;
          
        }
        
        manage = this.buttonGroup2.getElements();
        for(j=0; j < this.buttonGroup2.getButtonCount(); j++){
          if(manage.nextElement().isSelected()) break;
          
        }
        
        if(j==this.buttonGroup2.getButtonCount() || i==this.buttonGroup1.getButtonCount()) System.out.println("Select something, please!");
        else{
            int numElevador = edificio.acessElevatorAt(i, j);
            if(numElevador != -1)
               painelDoPainel.setText("Obrigado por esperar!!!\nSeu Elevador será o:  "+numElevador + "\nAguarde...");
            else
               painelDoPainel.setText("Credenciais inválidas!!\nPeça novamente e insira\nos números corretos!");
    
            painelDoPainel.setFont(painelDoPainel.getFont().deriveFont(18.0f));

        }
        //System.out.println(i + "    " + j);
    }//GEN-LAST:event_chamaElevadorPainelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfacePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfacePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfacePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfacePainel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfacePainel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton chamaElevadorPainel;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton10;
    private javax.swing.JRadioButton jRadioButton11;
    private javax.swing.JRadioButton jRadioButton12;
    private javax.swing.JRadioButton jRadioButton13;
    private javax.swing.JRadioButton jRadioButton14;
    private javax.swing.JRadioButton jRadioButton15;
    private javax.swing.JRadioButton jRadioButton16;
    private javax.swing.JRadioButton jRadioButton17;
    private javax.swing.JRadioButton jRadioButton18;
    private javax.swing.JRadioButton jRadioButton19;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton20;
    private javax.swing.JRadioButton jRadioButton21;
    private javax.swing.JRadioButton jRadioButton22;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    private javax.swing.JRadioButton jRadioButton7;
    private javax.swing.JRadioButton jRadioButton8;
    private javax.swing.JRadioButton jRadioButton9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea painelDoPainel;
    // End of variables declaration//GEN-END:variables
}
